# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Top.xdc

# IP: ip/fcompare/fcompare.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fcompare || ORIG_REF_NAME==fcompare} -quiet] -quiet

# IP: ip/float_to_fixed/float_to_fixed.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==float_to_fixed || ORIG_REF_NAME==float_to_fixed} -quiet] -quiet

# IP: ip/fixed_to_float/fixed_to_float.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fixed_to_float || ORIG_REF_NAME==fixed_to_float} -quiet] -quiet

# IP: ip/fdiv/fdiv.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fdiv || ORIG_REF_NAME==fdiv} -quiet] -quiet

# IP: ip/fmult/fmult.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fmult || ORIG_REF_NAME==fmult} -quiet] -quiet

# IP: ip/falu/falu.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==falu || ORIG_REF_NAME==falu} -quiet] -quiet
