# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Trinity/Documents/Vivado/sin_final/.Xil/Vivado-10952-DESKTOP-CHGJLHT/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.cache/wt [current_project]
set_property parent.project_path C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Trinity/Documents/Vivado/sin_final/sin_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/global_define.v
set_property file_type "Verilog Header" [get_files C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/global_define.v]
set_property is_global_include true [get_files C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/global_define.v]
read_mem C:/Users/Trinity/Documents/Vivado/sin_final/memory.dat
read_verilog -library xil_defaultlib {
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/DECL7S.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/alu.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/clock_transformer.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/condition_registers.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/datapath.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/decoders.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/etc.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/flu.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/io_module.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/main_controller.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/memory_controller.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/mlu.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/registers.v
  C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/new/mips.v
}
read_ip -quiet C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/ip/fcompare/fcompare.xci

read_ip -quiet C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/ip/float_to_fixed/float_to_fixed.xci

read_ip -quiet C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/ip/fixed_to_float/fixed_to_float.xci

read_ip -quiet C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/ip/fdiv/fdiv.xci

read_ip -quiet C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/ip/fmult/fmult.xci

read_ip -quiet C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/sources_1/ip/falu/falu.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/constrs_1/imports/new/Top.xdc
set_property used_in_implementation false [get_files C:/Users/Trinity/Documents/Vivado/sin_final/sin_final.srcs/constrs_1/imports/new/Top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
